#!/usr/bin/env bash
# Usage: 91 rails-backbone
# Summary: Add backbone to our rails app.
# Help: Add backbone to our rails app.
# Also adds haml_coffee_assets for the templates.

set -e

HOME="$PWD"
APP="${PWD##*/}" # get app name (or directory name)


echo "--- add haml_coffee_assets"

SOURCE="$_91_ROOT/share/rails/haml.coffee"
TARGET="$PWD/Gemfile"

cat $SOURCE >> $TARGET

bundle install


echo "--- init haml_coffee_assets"

echo "//= require hamlcoffee" >> $PWD/app/assets/javascripts/application.js


echo "--- add backbone"

echo "gem \"backbone-on-rails\"" >> Gemfile

bundle install


echo "--- run backbone setup"

rails g backbone:install


# ---------------------------------

# echo "--- init backbone"

# SOURCE="$_91_ROOT/share/rails/backbone.coffee"
# TARGET="$PWD/app/assets/javascripts/backbone/$APP.js.coffee"

# cat $SOURCE >> $TARGET

# get app name capitalized (e.g. 'sofa' >> 'Sofa')
# APPNAME=$(echo "$APP" | python -c "print raw_input().capitalize()")

# echo "  $APPNAME.init()" >> $TARGET
